/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: e1ef4e21ed80af34eae28df24511c532)
// Regenerate after every wrangler.jsonc `vars` change. Move .dev.vars aside
// first: wrangler folds it in, which would leak local-only vars into this file.
// Secrets and optional vars stay out on purpose; src/worker.ts declares them.
interface __BaseEnv_Env {
	UWU: KVNamespace;
	CLICKS: KVNamespace;
	DB: D1Database;
	CLICK_EVENTS: AnalyticsEngineDataset;
	CLERK_ISSUER: "https://clerk.uwu.land";
	STRIPE_PRICE_ID_MONTHLY: "price_1Tskr37kD2hzdcxngrmTlz91";
	STRIPE_PRICE_ID_YEARLY: "price_1TskrM7kD2hzdcxnG7VOskcx";
	STRIPE_PRICE_ID_LIFETIME: "price_1Tx4Fn7kD2hzdcxnuVyGUTgo";
	STRIPE_PRICE_ID_LIFETIME_LAUNCH: "price_1Tx6WA7kD2hzdcxn2llwVW1Q";
	STRIPE_LAUNCH_COUPON_ID: "LAUNCH25";
	ENFORCEMENT: DurableObjectNamespace<import("./worker").Enforcement>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "Enforcement";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
