/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: 470605180f6ccd93c7f54aff34f608f6)
// Regenerate with `wrangler types` after updating the Stripe vars.
interface __BaseEnv_Env {
	UWU: KVNamespace;
	CLICKS: KVNamespace;
	DB: D1Database;
	CLICK_EVENTS: AnalyticsEngineDataset;
	CLERK_ISSUER: "https://clerk.uwu.land";
	STRIPE_PRICE_ID_MONTHLY: "price_REPLACE_ME";
	STRIPE_PRICE_ID_YEARLY: "price_REPLACE_ME";
	ENFORCEMENT: DurableObjectNamespace<import("./worker").Enforcement>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "Enforcement";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
